#!/bin/sh

# Do not beep
xset b off

# Start X compositor daemonized (if existing in PATH)
#compton -b
xcompmgr -I.1 -O.08 -D10 -t-5 -l-5 -r12 -o.5 -CcFf &

# Launch dzen script if available
#[[ -x ~/.dzen.sh ]] && ~/.dzen.sh &

# Nitrogen restores the background
nitrogen --restore &

# Dunst for the desktop notification
dunst -config ~/.config/dunst/dunstrc &

# Tint2 and Conky for Openbox
tint2 &
conky &

